### ISSUE TITLE
Add to AUR repo?

### ISSUE THREAD

**Issue by ca5ua1** [tralph3/ZeroTier-GUI#1]

**Comment by tralph3** [comment]
The ZeroTier team said they have interests in packaging the GUI into their official repos. I'm holding from creating an AUR repo because it would be better that way. Plus I don't have experience with AUR repos, nothing I couldn't learn of course.

**Comment by ghost** [comment]
It's now April 2021, and I see no mention of ZeroTier packaging this in their repo?

If you can add a PKGBUILD to AUR, that would be great! It would also give this more exposure.

**Comment by tralph3** [comment]
Surely. It'd be good for me to learn how to package stuff to the aur. When I get some free time one of these days I'll look into it. I think I'll give up on compiling python, I'll just symlink the executable to /usr/bin
