### ISSUE TITLE
root privileges

### ISSUE THREAD

**Issue by wpinacz** [tralph3/ZeroTier-GUI#10]
Hi,
I'm facing a problem running zerotier-gui using Ubuntu (20.04).
The problem is with root privileges, zerotier-gui isn't asking for password, just throwing "zerotier-cli: authtoken.secret not found or readable in /var/lib/zerotier-one (try again as root)"
For sure "sudo zerotier-gui" works but I think that GUI app should be run from os GUI.....
Tried to chenge .desktop file exec line with: "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /usr/bin/zerotier-gui"  , after running and entering password zerotier-gui doesn't show, entering "pkexec...." from command line works.
Any idea how to solve this puzzle?

Thanx.

**Comment by tralph3** [comment]
So, in order to grant access to a regular user to ZeroTier, you need to have the authorization token in your home folder. The program should check if you have it, and create it if you don't. For this, it asks you for root permission with pkexec, here's the relevant piece of code:

    system( f'pkexec bash -c "cp /var/lib/zerotier-one/authtoken.secret '\
        f'/home/{username}/.zeroTierOneAuthToken && chown {username} '\
        f'/home/{username}/.zeroTierOneAuthToken && chmod 0600 '\
        f'/home/{username}/.zeroTierOneAuthToken"'
    )

As you can see, all it does is copy that file and give you permissions.

Now, you say pkexec isn't working with the program, but it does work with the terminal. Does running the GUI through the terminal show any other error? Maybe it's failing somehow.

**Comment by wpinacz** [comment]
> So, in order to grant access to a regular user to ZeroTier, you need to have the authorization token in your home folder. The program should check if you have it, and create it if you don't. For this, it asks you for root permission with pkexec, here's the relevant piece of code:
> 
> ```
> system( f'pkexec bash -c "cp /var/lib/zerotier-one/authtoken.secret '\
>     f'/home/{username}/.zeroTierOneAuthToken && chown {username} '\
>     f'/home/{username}/.zeroTierOneAuthToken && chmod 0600 '\
>     f'/home/{username}/.zeroTierOneAuthToken"'
> )
> ```
> 
> As you can see, all it does is copy that file and give you permissions.
> 
> Now, you say pkexec isn't working with the program, but it does work with the terminal. Does running the GUI through the terminal show any other error? Maybe it's failing somehow.

Hi,
now it works, without pkexec.... in .desktop file.
I think I saw somewhere on zertier support site that versions above ~1.6.0 have changed root privileges policy, earlier I had zerotier (below 1.6.0) with zerotier-gui on another pc (same ubuntu 20.04) and worked without a hassle.
Maybe there should be Yours script included in Install.sh or  included 2nd .....fix_root_permissions.sh into installer so any1 else could easy fix same problems.
Anyway problem fixed.
Thank You for Your support.

Regards.

**Comment by tralph3** [comment]
What would be the new root privileges policy?

**Comment by wpinacz** [comment]
> What would be the new root privileges policy?

Sorry, it wasnt on zerotier support, it was here on github, the problem exists in >= 1.4.0
Here's the link:
https://github.com/zerotier/ZeroTierOne/issues/996

It's just the policy for normal users, just what Your script does fixing problem.
