### ISSUE TITLE
DNS Config checkbox

### ISSUE THREAD

**Issue by Pawel095** [tralph3/ZeroTier-GUI#18]
Since version 1.6.0 of zerotier there is a way to configure DNS servers. It has to be enabled by clients.

I'd like to propose adding a checkbox to network settings to enable or disable DNS configuration, similar to 1.8.1-windows version of zerotier client.(Image below).
![image](https://user-images.githubusercontent.com/6631902/140721416-b5c28c83-2f50-4638-8a2a-3291c179722d.png)

**Comment by tralph3** [comment]
Yeah, why not. This should be a pretty trivial addition.

**Comment by Pawel095** [comment]
I just had a look at the code, It should be identical to what other checkboxes do already, only command argument is different. As soon as I find the docs, I'll edit this comment and add it.

Edit: The comand is in the change log, end of first point. https://www.zerotier.com/2020/10/09/zerotier-1-6-0-beta1-released/

**Comment by tralph3** [comment]
I actually just pushed the update. Thanks for the heads up, I wasn't aware of this new option.
