### ISSUE TITLE
zerotier-gui expected but zerotier-gui.py is the one being redistributed.

### ISSUE THREAD

**Issue by IlabSentuser** [tralph3/ZeroTier-GUI#8]
Hello. Is a pretty simple detail and with an extremely simple fix, but someone may not notice it a first and fail. In the install script and the .desktop file you have zerotier-gui and the name of the file is zerotier-gui.py. So without a minor user intervention it is not working as expected. I report it just so you know, very nice gui, thanks.

**Comment by tralph3** [comment]
Yes this is in fact an oversight on my part, but it's not entirely wrong. The script is intended to be used with the compiled versions found in the releases, which don't include the .py extension. I could probably make a quick check to see which of the two is present and move them accordingly.
